framework:
  messenger:
    default_bus: command_bus

    buses:
      command_bus:
        default_middleware:
          enabled: true

      query_bus:
        default_middleware:
          enabled: true

      event_bus:
        default_middleware:
          enabled: true

    transports:
      async: '%env(MESSENGER_TRANSPORT_DSN)%'
      failed:
        dsn: 'doctrine://default?queue_name=failed'

    routing:
    # асинхронные события домена отправляются в RabbitMQ
